export const FETCH_LIST_REQUEST = "FETCH_LIST_REQUEST";
export const FETCH_LIST_SUCCESS = "FETCH_LIST_SUCCESS";
export const FETCH_LIST_FAILURE = "FETCH_LIST_FAILURE";
export const TOGGLE_COMPLETION_REQUEST = "TOGGLE_COMPLETION_REQUEST";
export const TOGGLE_COMPLETION_SUCCESS = "TOGGLE_COMPLETION_SUCCESS";
export const TOGGLE_COMPLETION_FAILURE = "TOGGLE_COMPLETION_FAILURE";
